### ISSUE TITLE
this.$('select') not found

### ISSUE THREAD

**Issue by flanamacca** [aldeed/meteor-autoform-select2#15]
TypeError: undefined is not a function
    at Template.afSelect2_bootstrap3.rendered (http://localhost:3020/packages/aldeed_autoform-select2.js?5459471e26ddb2f71a080971cf00a98dcc40191b:255:20)

**Comment by yogiben** [comment]
I'm getting the same.

Even when I copy manually add the select2 library, it seems to have trouble.

**Comment by aldeed** [comment]
Make sure `natestrauser:select2` comes before this package in your packages file, or make sure the library is loading before all templates that contain this form component.

**Comment by aldeed** [comment]
Closing. Please provide a reproduction repo or MeteorPad if you're still having trouble.

**Comment by thebarty** [comment]
bumper - I just ran into this issue after migriting to 1.3.

Thats what I tried so far (NON if it worked)

1) Manually include select2 (this DOES NOT work in 1.3)
```
if (Meteor.isClient) {
  require( './client/vendors/select2/select2.min.js' )
}
```

2) Install via NPM an require (does NOT work)
``meteor npm install --save select2``
and then
```
if (Meteor.isClient) {
  require( 'select2' )
}
```

Does anyone have a fix?
