### ISSUE TITLE
Not working with meteor 1.3-rc.2

### ISSUE THREAD

**Issue by PositronicBrain** [aldeed/meteor-autoform-select2#65]
select2.min.js:1 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ select2.min.js:1m @ select2.min.js:1j @ select2.min.js:1m @ select2.min.js:1j @ select2.min.js:1n @ select2.min.js:1(anonymous function) @ select2.min.js:2(anonymous function) @ select2.min.js:2
msavin_mongol.js?hash=de54bdf…:1338 'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.

**Comment by PositronicBrain** [comment]
It seems to work if you add 

    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-rc.1/css/select2.min.css" rel="stylesheet" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0-rc.1/js/select2.min.js"></script>

To `<body>` instead of `<head>`

**Comment by odb366** [comment]
Hey thanks, that solved the problem!

**Comment by thebarty** [comment]
Hi guys,

I just ran into this issue after migriting to 1.3. and thanks for providing this workaround.
I would much prefer Option 2) to work with meteor 1.3... 

With Option 1) an 2) I am getting a 
```
TypeError: $s.select2 is not a function
    at Template.afSelect2.rendered (aldeed_autoform-select2.js:210)
```

Option 1) FAILS: Manually include select2 (this DOES NOT work in 1.3)

if (Meteor.isClient) {
  require( './client/vendors/select2/select2.min.js' )
}

Option 2) FAILS: Install via NPM an require (does NOT work)
meteor npm install --save select2
and then

if (Meteor.isClient) {
  require( 'select2' )
}

Option 3) WORKS: use @PositronicBrain s fix

**Comment by comerc** [comment]
other workaround
```javasript
  onRendered: ->
    $.getScript '/countdown.js', ->
      $('.countdown').countdown date: new Date 2016, 5, 15
```

**Comment by mbabauer** [comment]
@thebarty, what is Option 3?  I only see two options listed

**Comment by thebarty** [comment]
@mbabauer check out the second post in this topic

**Comment by macrozone** [comment]
just updated an old app to meteor 1.4.*
and now i get: $s.select2 is not a function

I added select2 to the body as written above

**Comment by macrozone** [comment]
also with meteor 1.2.1 this does not work anymore

**Comment by aldeed** [comment]
Latest release and instructions are confirmed to work with latest Meteor
